### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by asedlmayr**
Adding some configuration files and other general bug fixes.

### CODE REVIEW

**Review by obejarano — COMMENTED** [review]
I was a bit surprised by the 25Mbps rate in the UHD config. @rdoosty do you know if he has tested it?

**Comment by tingjunchen** [comment]
@obejarano for Sounder I can do up to 50 MSa/s on USRP X310 and 62.5 MSa/s on USRP N310 in the SISO setting (both with 10G sfp+ ports), or 25 MSa/s on USRP X310 and 31.25 MSa/s on USRP N310 in the 2x2 MIMO setting. This has been tested. Please note that I haven't tested the UHD part with large MIMO configurations yet

**Review by obejarano — COMMENTED** [review]
@tingjunchen that's great! good to know. thanks for replying.

**Review by obejarano — APPROVED** [review]
all good

**Pull request merged**
