### PR TITLE
Pr double free

### LINKED ISSUE #30: double free or corruption (out) error while syncing
Double free or corruption fault while running on some servers.   The issue has been seen multiple times but comes and goes.  Indicative of writing out of an array bounds.

gdb displays the backtrace of the free memory pointers at the end of client sync tx in receiver.cc

### LINKED ISSUE #33: VS code workspace file
Provide a VS Code workspace file.

### PR DESCRIPTION
**Pull request by asedlmayr**
Resolves #30 , resolves #33 
Add logging interface (Compile time removal)
Add VS Code workspace file
Modified vector accesses to .at() instead of [] to catch memory overruns (might be performance implications)
Modified the config class interface and variable names
Added Build type and logging levels to the cmake options

### CODE REVIEW

**Review by rdoosty — COMMENTED** [review]
I tested the code and it works for me. Also a lot of improvement. Thanks, Andrew!
Just one comment: I see you switched to 80 characters per line format similar to Agora in some of the files (e.g. ClientRadioSet.cc and BaseRadioSet.h). Care to do the same for other files too?

**Comment by asedlmayr** [comment]
Updated the clang-format for 80 column width and ran it over the c++ source files.

**Comment by rdoosty** [comment]
Great, thanks! Let me merge this.

**Review by rdoosty — APPROVED** [review]

**Comment by rdoosty** [comment]
Actually, just remembered one more thing. In `recv` function in `Radio.cc`, can we replace the second `MLPD_ERROR` with `MLPD_WARN`? We get some of this in the beginning of the run, and that could confuse an experimenter.

**Comment by asedlmayr** [comment]
Updated the readStream less bytes than expected from ERROR to WARN

**Review by rdoosty — APPROVED** [review]

**Pull request merged**
