### PR TITLE
Pr embedded json

### PR DESCRIPTION
**Pull request by asedlmayr**
Updated the queue, embedded the json files and added the include path the to cmake file

### CODE REVIEW

**Comment by asedlmayr** [comment]
Updated third party libraries.  
Removed option to disable json.  
Enabled comments in json files

**Review by rdoosty — COMMENTED** [review]
Should we create a new repo for the reduced JSON library and pull as a submodule to both RENEWLab and Agora? There seem to be a lot of files here.

**Comment by asedlmayr** [comment]
> 
> 
> Should we create a new repo for the reduced JSON library and pull as a submodule to both RENEWLab and Agora? There seem to be a lot of files here.

There are three options.  
1.  Pull in all the release file (like i did).  Total size: ~2MB
2.  Use only the single include file (926kB)
3.  Use the submodule method on the reduced library (sub modules require a little bit of user intervention to keep them up to date but not a huge concern. (https://github.blog/2016-02-01-working-with-submodules/)

I am ok with any of the approaches

**Comment by rdoosty** [comment]
I agree about the submodule approach needing to be updated manually. My main concern was adding a significant number of files to both Agora and RENEWLab separately. I am not sure how that exactly works, but why not approach 2 with a single JSON file? That seems more reasonable to me.

**Comment by asedlmayr** [comment]
Moved to option #2.

**Comment by asedlmayr** [comment]
Moved to option #2.

**Pull request closed without merging**
